### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by WangxiaowuLab** [tjs23/nuc_processing#12]
Hello!
I want to convert my hic contact data to NCC format,but I don't know how to get the line "The number of the ambiguity group to which the paired reads belong" and "Whether read pairs are swapped relative to original FASTQ files".Can you help me ? Thank you

**Comment by tjs23** [comment]
As long as your Hi-C data does not contain any ambiguous/multi-mapping contacts then the ambiguity group number can simply be set to any unique integer value, for example you could use the line number or re-use the sequencing read number. The latter is also handy if your data actually are multi-mapping.

Please note that in the future the NCC format will be changing here; rather than grouping ambiguous contacts by a unique group number the format will have ordered lines and will use a {group_size}.{is_selected} style format. (For example a normal, single-mapping contact will use "1.1" for the ambiguity field.) This format change allows for contact pair selection/deselection without loss of information and the ability to arbitrarily concatenate files. The new NCC adjusted format is already being used by the development branches of nuc_processing, nuc_tools and nuc_dynamics).

For the read-swap field this can simply be set to 0 if you're converting from another format. Though not required for structure calculation etc. this value is handy, along with the read number, for working out exactly where a contact end came from. (It would be 0 for Read1-Read2 pairs and 1 for Read2-Read1 pairs if the NCC file were created with nuc_processing)

Hope this helps,

T.
